68-Concluir páginas
fga-eps-mds/2019.2-Questmark pull request #71
Opened 2019-10-16 01:41 UTC by nicaloribeiro

# Issue Relacionada
* Esse *pull request* resolve a issue #68

# Tipo de mudança
- [ ] Bugfix  
- [x] Nova funcionalidade  
- [ ] Alteração de funcionalidade
- [ ] Outro

# Descrição
* As páginas descritas na issue foram criadas inicialmente em HTML e CSS e, posteriormente, o HTML foi convertido e para EJS e a lógica em JavaScript referente à página para seu funcionamento planejado foi aplicado.

# Comentários
* Será necessário rever com a equipe o real layout e conteúdo da página de ajuda.

2019-10-16 01:45 UTC, lucaslop requested changes
Resolver os respectivos conflitos para o pull request

2019-10-16 02:05 UTC, nicaloribeiro commented
@lucaslop @Gustavo-Nogueira Mudanças realizadas, por favor verificar se elas estão corretas e informar caso novas mudanças sejam necessárias.

2019-10-16 02:14 UTC, lucaslop requested changes
Realizar As seguintes alterações:

- Colocar o caminho(s) relativos no backend ( das views)
- Colocar o caminho(s) relativos dos arquivos estáticos 
- Página fora da pasta
- Páginas em .html

2019-10-16 02:14 UTC, lucaslop commented on frontend/views/help/pagina_de_ajuda.html
> +    <link rel="stylesheet" href="../../public/cadastro_formulario/style/header.css">
Não está pegando os arquivos. Os arquivos estáticos já estão definidos como o diretório publico, então é necessário o caminho relativo

2019-10-16 02:14 UTC, lucaslop commented on frontend/views/help/pagina_de_ajuda.html
> +<!DOCTYPE HTML>
A pagina está em .html

2019-10-16 02:14 UTC, lucaslop commented on frontend/views/formularios/cadastro_formulario.ejs
> +	<link rel="stylesheet" href="../../public/cadastro_formulario/style/novoformulario.css">
Não está pegando os arquivos. Os arquivos estáticos já estão definidos como o diretório publico, então é necessário o caminho relativo

2019-10-16 02:14 UTC, lucaslop commented on frontend/views/Header.html
> +    <link rel="stylesheet" href="../../public/cabecalho/style/header.css">
Não está pegando os arquivos estáticos . Os arquivos estáticos já estão definidos como o diretório publico, então é necessário o caminho relativo

2019-10-16 02:14 UTC, lucaslop commented on backend/routes/forms.js
> +        res.render("../../frontend/views/formularios/visualizar_formulario",{name_quest: formulario.nome,
O caminho das rotas já foi definido lá nas configurações do template. Deve assumir que já estará no arquivo views. Não deve colocar o caminho completo para o arquivo. Por questões de boas praticas e padrão do código.

2019-10-16 02:15 UTC, lucaslop commented on frontend/views/help/pagina_de_ajuda.html
> +    <link rel="stylesheet" href="../../public/cadastro_formulario/style/header.css">
Além disso, a pagina está em .html

2019-10-17 01:21 UTC, DanilloGS reviewed
@lucaslop, solicitando uma nova revisada no PR

2019-10-17 05:27 UTC, lucaslop commented on frontend/views/Header.html
> +    <link rel="stylesheet" type="text/css" href="../public/header/styles/header.css">
Esse arquivo está em .html

2019-10-17 12:07 UTC, lucaslop commented
Após as modificações solicitadas. o PR foi aceito.

2019-10-17 12:07 UTC, merged