75 - Recuperação de senha
fga-eps-mds/2019.2-Questmark pull request #83
Opened 2019-10-23 03:15 UTC by nicaloribeiro

# Issue Relacionada
* Esse *pull request* resolve a issue #75

# Tipo de mudança
- [ ] Bugfix  
- [x] Nova funcionalidade  
- [ ] Alteração de funcionalidade
- [ ] Outro

# Descrição
Foram feitas as rotas para recuperação de senha. Esse processo ocorre da seguinte forma :
* Primeiramente é passado um e-mail como parâmetro;
* Caso o e-mail exista, é gerado um *token* com tempo de expiração definido em 1 hora;
* Esse *token* é salvo no banco de dados no usuário que requisitou a troca de senha;
* Utilizando-se do *token*, o usuário pode trocar sua senha;

Lembrando que está apenas no *backend*. Existe uma rota para gerar o *token* e outra para recuperar senha a partir do *token*.
Para fins de teste, está sendo usado o MailTrap e o e-mail está sendo enviado corretamente com o *token* via *nodemailer*.

2019-10-23 14:05 UTC, lucaslop requested changes
Ao clicar no botão  _**esqueci minha senha**_ na rota de login, 

  redireciona para a rota **./CriarCadastro.html** e ela não existe.

2019-10-23 14:22 UTC, nicaloribeiro commented
@lucaslop Esse redirecionamento não foi feito nessa issue  e não há ainda front end para a recuperação de senha. A issue se trata da funcionalidade apenas no backend, e está pronto. Nas próximas apronta deve haver alguma issue para criar o front end para recuperar senha e organizar os redirecionamentos.

2019-10-23 14:27 UTC, lucaslop commented
> @lucaslop Esse redirecionamento não foi feito nessa issue e não há ainda front end para a recuperação de senha. A issue se trata da funcionalidade apenas no backend, e está pronto. Nas próximas apronta deve haver alguma issue para criar o front end para recuperar senha e organizar os redirecionamentos.

Como devo testar a recuperação de email?

2019-10-23 14:33 UTC, nicaloribeiro commented
@lucaslop Existem algumas ferramentas para se testar APIs enviando apenas as requisições HTTP. No meu caso, eu utilizei o [Postman](https://www.getpostman.com/) pois é o que eu tenho mais familiaridade. Outra que conheço e que posso recomendar é o [Insomnia](https://insomnia.rest/).

2019-10-24 18:56 UTC, lucaslop approved these changes
Aprovado após testes manuais

2019-10-24 18:56 UTC, merged